<p>
    <label for="wp_disable_page_checkbox" class="post-attributes-label">
        <input type="checkbox" name="disable_page" id="wp_disable_page_checkbox" value="1" /> 
        <strong>Disable Page</strong>
    </label>
</p>
<p>
    <label for="wp_disable_page_url">
        <strong>Redirect To:</strong>
    </label><br />
    <input type="text" name="disable_page_url" style="width: 100%;" />
</p>